[package]
name = "allpostgres"
version = "0.1.0"
authors = ["spiderman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
tokio = { version = "0.2", features = ["full"] }
